[versions]

# Paper
paper = "1.19.1-R0.1-SNAPSHOT"
paper-lib = "1.0.8-SNAPSHOT"

# Kyori
kyori-api = "4.11.0"

# Misc
bstats = "3.0.0"
nbt-api = "2.10.0"

# YAML
yaml = "1.8"

# Guice
guice = "5.1.0"

# Holograms
holographic-displays = "2.4.9"
decent-holograms = "2.5.2"

# Placeholders
mvdw-placeholder-api= "3.1.1-SNAPSHOT"
placeholder-api = "2.11.2"

# Truly random
apache-commons = "1.9"
vault-api = "1.7"

# Triumph Team
cmds = "2.0.0-SNAPSHOT"
gui = "3.1.2"

[libraries]

# PaperMC
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
paper-lib = { module = "io.papermc:paperlib", version.ref = "paper-lib" }

# Kyori
kyori-api = { module = "net.kyori:adventure-api", version.ref = "kyori-api" }
mini-message = { module = "net.kyori:adventure-text-minimessage", version.ref = "kyori-api" }

# BStats Bukkit
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

# YAML
yaml = { module = "me.carleslc.Simple-YAML:Simple-Yaml", version.ref = "yaml" }

# Guice
guice = { module = "com.google.inject:guice", version.ref = "guice" }

# Holograms
holographic-displays = { module = "com.gmail.filoghost.holographicdisplays:holographicdisplays-api", version.ref = "holographic-displays" }
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decent-holograms" }

# Placeholders
mvdw-placeholder-api = { module = "be.maximvdw:MVdWPlaceholderAPI", version.ref = "mvdw-placeholder-api" }
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }

# NBT API
nbt-api = { module = "de.tr7zw:nbt-data-api", version.ref = "nbt-api" }

# Truly Random
apache-commons = { module = "org.apache.commons:commons-text", version.ref = "apache-commons" }

vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault-api" }

# Triumph Team
triumph-bukkit = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "cmds" }

triumph-gui-bukkit = { module = "dev.triumphteam:triumph-gui", version.ref = "gui" }