[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
# Paper API
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Kyori API
kyori-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Plugin API
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decentholograms" }
headdatabaseapi = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabaseapi" }
itemsadder = { module = "com.github.LoneDev6:api-itemsadder", version.ref = "itemsadder" }
fancy-holograms = { module = "de.oliver:FancyHolograms", version.ref = "fancyholograms" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }
cmi-api = { module = "CMI-API:CMI-API", version.ref = "cmi-api" }
cmi-lib = { module = "CMILib:CMILib", version.ref = "cmi-lib" }
nexo = { module = "com.nexomc:nexo", version.ref = "nexo" }

# Plugin API
excellentcrates = { module = "su.nightexpress.excellentcrates:ExcellentCrates", version = "5.3.1" }
nightcore = { module = "su.nightexpress.nightcore:nightcore", version = "2.6.3" }

# Fusion Core API
fusion-paper = { module = "com.ryderbelserion:fusion-paper", version.ref = "fusion" }
fusion-core = { module = "com.ryderbelserion:fusion-core", version.ref = "fusion" }

# Common API
triumph-cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "triumph-cmd" }
jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }
metrics = { module = "org.bstats:bstats-bukkit", version.ref = "bStats" }
jalu = { module = "ch.jalu:configme", version.ref = "jalu" }

[versions]
# Paper API
paper = "1.21.4-R0.1-SNAPSHOT"
minecraft = "1.21.4"

# Gradle Plugins
shadow = "9.0.0-beta4"
paperweight = "1.7.7"
runPaper = "2.3.1"
minotaur = "2.8.7"
hangar = "0.1.2"

# Plugin API
decentholograms = "2.8.8"
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.6"
fancyholograms = "2.4.1"
nexo = "0.5.0-dev.14"
itemsadder = "3.6.1"
cmi-api = "9.7.4.1"
cmi-lib = "1.5.1.4"
oraxen = "1.171.0"

# Fusion API
fusion = "0.1.0"

# Common API
triumph-cmd = "2.0.0-ALPHA-10"
jetbrains = "24.1.0"
bStats = "3.1.0"
jalu = "1.4.1"

# Kyori API
adventure = "4.17.0"

[bundles]
# Soft Depend
dependencies = ["decent-holograms", "fancy-holograms", "cmi-lib", "cmi-api"]

# Shared API
shared = ["headdatabaseapi", "placeholderapi", "itemsadder", "oraxen", "nexo"]

# Adventure API
adventure = ["kyori-api", "kyori-text", "kyori-logger"]

# Crate API
crates = ["excellentcrates", "nightcore"]