[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.3.0" }

[versions]
# Kotlin
kotlin = "1.9.24"

# Minecraft
paper = "1.20.6-R0.1-SNAPSHOT"
paperweight = "1.7.1"
adventure = "4.17.0"

# Plugins
itemsadder = "3.6.3-beta-14"
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.5"
oraxen = "1.171.0"

# Core
annotations = "24.1.0"
crazycrates = "0.5"
jalu = "1.4.1"
yaml = "1.8.4"
vital = "1.2"

decentholograms = "2.8.8"
fancyholograms = "2.0.6"

triumph-cmd = "2.0.0-ALPHA-10"
tirumph-gui = "3.1.7"

vault = "1.7.1"

[libraries]
# Paper
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Plugins
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decentholograms" }
fancy-holograms = { module = "de.oliver:FancyHolograms", version.ref = "fancyholograms" }

headdatabaseapi = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabaseapi" }
placeholderapi = { module = "com.github.LoneDev6:api-itemsadder", version.ref = "itemsadder" }

vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }

itemsadder = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }

# Libraries
triumph-cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "triumph-cmd" }
triumph-gui = { module = "dev.triumphteam:triumph-gui", version.ref = "tirumph-gui" }

crazycrates = { module = "us.crazycrew.crazycrates:api", version.ref = "crazycrates" }

vital-paper = { module = "com.ryderbelserion.vital:paper", version.ref = "vital" }
vital-core = { module = "com.ryderbelserion.vital:core", version.ref = "vital" }

[bundles]
holograms = ["decent-holograms", "fancy-holograms"]

triumph = ["triumph-cmds", "triumph-gui"]

items = ["itemsadder", "oraxen"]