# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ legacy ]
  pull_request:
    branches: [ legacy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Spigot 1.8
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.8.8
        
    - name: Spigot 1.10
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.10.2 --compile Spigot
        
    - name: Spigot 1.11
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.11.2 --compile Spigot
        
    - name: Spigot 1.12
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.12.2 --compile Spigot
        
    - name: Spigot 1.13
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.13.2 --compile Spigot
        
    - name: Spigot 1.14
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.14.4 --compile Spigot
                
    - name: Spigot 1.15
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.15.2 --compile Spigot
                        
    - name: Spigot 1.16
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.16.5 --compile Spigot
                      
    - uses: actions/setup-java@v2
      with:
        # This version should probably match the ones from the 'run'-job
        java-version: 17
        distribution: temurin
                                
    - name: Spigot 1.17
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        java -jar BuildTools.jar --rev 1.17.1 --compile Spigot
                              
    - uses: actions/setup-java@v2
      with:
        # This version should probably match the ones from the 'run'-job
        java-version: 8
        distribution: temurin
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
