name: '${name}'
main: '${group}.CrazyCratesPaper'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'
folia-supported: true

softdepend: [CMI, DecentHolograms, HolographicDisplays, PlaceholderAPI, ItemsAdder, Oraxen]